/**
 ******************************************************************************
 *
 * @file       /Users/buzz/UAV/TauLabs/build/fw_quanton/fw_quanton.bin.firmwareinfo.c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2011.
 * @brief      Firmware version info file autogenerated using template
 *             /Users/buzz/UAV/TauLabs/make/templates/firmwareinfotemplate.c
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include <stdint.h>

/**
 * We have 100 bytes for the whole description.
 *
 *
 * Structure is:
 *   4 bytes: header: "TlFw".
 *   4 bytes: GIT commit tag (short version of SHA1).
 *   4 bytes: Unix timestamp of compile time.
 *   2 bytes: target platform. Should follow same rule as BOARD_TYPE and BOARD_REVISION in board define files.
 *  26 bytes: commit tag if it is there, otherwise branch name. '-dirty' may be added if needed. Zero-padded.
 *  20 bytes: SHA1 sum of the firmware.
 *  20 bytes: SHA1 sum of the uavo definitions.
 *  20 bytes: free for now.
 *
 */

struct __attribute__((packed)) fw_version_info {
	uint8_t magic[4];
	uint32_t commit_hash_prefix;
	uint32_t timestamp;
	uint8_t board_type;
	uint8_t board_revision;
	uint8_t commit_tag_name[26];
	uint8_t sha1sum[20];
	uint8_t uavosha1[20];
	uint8_t pad[20];
};

const struct fw_version_info fw_version_blob __attribute__((used)) __attribute__((__section__(".fw_version_blob"))) = {
	.magic = { 'T','l','F','w' },
	.commit_hash_prefix = 0x48574591,
	.timestamp = 1388622613,
	.board_type = 0x86,
	.board_revision = 0x01,
	.commit_tag_name = "next",
	.sha1sum = { 0x29,0x76,0xbe,0x02,0x57,0x1c,0x28,0xeb,0x43,0x95,0xc5,0xc7,0xf0,0x78,0xa1,0x73,0x38,0x22,0x52,0xaa },
	.uavosha1 = { 0xd0,0x22,0x8d,0x61,0x6d,0x06,0x2b,0xe0,0x0a,0x4e,0xbe,0x1f,0xce,0xdb,0xd1,0xd7,0xf6,0xc5,0xa7,0xcb },
}; 

/**
 * @}
 */
